// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchFullText(arg1, arg2) {
  return window['go']['controller']['SearchController']['SearchFullText'](arg1, arg2);
}
