// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function SearchFullText(arg1:string,arg2:string):Promise<Array<controller.LocationsFile>>;
